Add type hints, docstrings, and expand test. Introduced bug fix in _define_variables
solegalli/feature_engine pull request #159
Opened 2020-10-10 10:09 UTC by Okroshiashvili

Here are all the type hints and docstrings which included in my previous PR. Moreover, I added some test cases and made some stylistic modifications. Additionally, the PR includes a bug fix for ```_define_variables()``` function and extra test cases to catch possible bugs.

2020-10-11 18:56 UTC, Okroshiashvili commented
@solegalli why 2216479 commit shows as it failed but the CI not?

2020-10-12 12:22 UTC, solegalli requested changes
Thank you so much for such an amount of work! This is really impressive. And I learned a lot from reviewing :)

I like how you use args, returns and raises in the docstrings, and the replacement by the genexp of the listscomps
Thanks a lot!

Could I ask for some general changes:

**1) Code style: black and flake8:**

We are using black and flake8 to keep code style. Would you mind running your scripts by black to unify style?

Should be:

```
from feature_engine.dataframe_checks import (
    _is_dataframe,
    _check_input_matches_training_df,
    _check_contains_na,
)
```

Instead of:
```

from feature_engine.dataframe_checks import (_check_contains_na,
                                             _check_input_matches_training_df,
                                             _is_dataframe)
```

As per black auto-formatting.

2) In all transformers (log, reciprocal, power, boxcox, base, etc) in the fit method, the argument y can be None or a pandas Series. I see that it says Optional string? can you check?

3) Docs: we are using british English, would you mind if we keep words with s instead of z, for example initialise instead of initialize. Not too sure is the best way forward, but we would have to change the entire documentation otherwise. Maybe we do that in a different PR?

4) in the init of almost every transformer (except MathCombination), the parameter variables can take a list of strings, a single string, or None. Optional(List[str]) means that it can take a list of strings. Do I understand this correctly? should it not be Union(List[str], str) = None instead?

5) imports shttps://www.python.org/dev/peps/pep-0008/#imports

Imports should be grouped in the following order:

    Standard library imports.
    Related third party imports.
    Local application/library specific imports.

We should put a blank line between each group of imports.(wich I don't always do :/)

After this, I will make a PR to your repo with some of these changes. Would you mind extending them to the rest of the scripts?

Or tell me otherwise if you disagree. 

Thank you!

2020-10-12 12:22 UTC, solegalli commented on feature_engine/wrappers/wrappers.py
modules from feature engine should be ordered at the end of the import, as per pep8. Could we re-order?

2020-10-14 07:20 UTC, Okroshiashvili commented
@solegalli I'm again late :) I will consider all the suggestions you made and will adjust my PR. I need some time to do all of these.

2020-10-17 05:33 UTC, Okroshiashvili commented on feature_engine/base_transformers.py
>  from feature_engine.variable_manipulation import _find_numerical_variables
I used black. Never tried before and looks amazing. Thanks for your suggestion. :)

2020-10-17 05:39 UTC, Okroshiashvili commented on feature_engine/base_transformers.py
> +            DataFrame with fitted transformation
In the initial source the ```fit()``` method returns DataFrame. I'm changing code that the ```fit()``` will return ```self```

2020-10-17 06:13 UTC, Okroshiashvili commented on feature_engine/transformation/boxcox.py
But here the existing None makes it difficult to only pass string or list of strings

2020-10-20 15:44 UTC, merged

2020-10-20 15:44 UTC, solegalli commented
@Okroshiashvili all good, merged! Thanks a lot!