support for pd.CategoricalDtype to determine categorical features in dataframe
solegalli/feature_engine pull request #260
Opened 2021-05-25 18:58 UTC by bitsbuffer

This PR contains changes for support of pd.CategoricalDtype to determine categorical features in dataframe along with dtype="object".

2021-05-26 11:59 UTC, solegalli requested changes
Hi @bitsbuffer, thank you so much for the PR. This is looking good. 

I have a few questions / requests:

- can we add a test to the specific function that you modified here: https://github.com/solegalli/feature_engine/blob/master/tests/test_variable_manipulation.py#L57
- why did you modify `df_vartypes` and `df_numeric` in the pytest config? Those dataframes are not used by the categorical encoders. I would modify either of the dataframes with `enc` in the name, and make sure that the categorical encoders tests pass.
- there are 2 other transformers that operate with categorical variables, the sklearnwrapper and the  SelectByTargetMeanPerformance. Can we make sure that those still work as expected after the changes?

Thanks a lot!

2021-05-26 11:59 UTC, solegalli commented on tests/test_creation/test_combine_with_reference_feature.py
>      # init params
combine with feature reference does not operate over categorical variables. i would not modify this tests.

2021-05-26 11:59 UTC, solegalli commented on tests/test_creation/test_mathematical_combination.py
>      # init params
same here, this test does not operate over categorical variables. I would try not to modify this test.

2021-05-26 14:48 UTC, bitsbuffer commented on tests/conftest.py
> +    df.loc[:, 1] = df.loc[:, 1].astype(cat_type)
I checked this right now, it seems you are correct there is no need to modify dtype here. I will update this and required test case (test_variable_names_when_df_cols_are_integers)

2021-05-29 08:19 UTC, solegalli commented
fyi #256 introduces a lot of changes to categorical encoders and tests. So we need rebase that branch and make the PR to check_estimator branch, or alternatively, wait until the other PR is merged.

Cheers

2021-06-07 13:02 UTC, solegalli commented
Hey @bitsbuffer 

I've now merged #256 into master. Would you be able to rebase master into this branch, and continue with the changes? If you need support with finding with df need to be modified in the tests, let me know

Cheers
Sole

2021-06-07 14:57 UTC, bitsbuffer commented
thanks @solegalli for the information. I will do the appropriate changes as suggested by you.

2021-06-10 11:52 UTC, closed without merging